version: "3.8"

services:
  frontend:
    container_name: frontend_dev
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app
    networks:
      - teo-network
    ports:
      - "3001:3001"
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: yarn run start:debug --preserveWatchOutput
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - teo-network
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  db:
    env_file:
      - .env.dev
    container_name: postgres_db
    image: postgres
    restart: always
    networks:
      - teo-network

networks:
  teo-network:
