version: "3.8"

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app
    networks:
      - teo-network
    ports:
      - "3001:3001"
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: ./backend/
      target: development
      dockerfile: Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - teo-network
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  teo-network:
